name: okeanos
channels:
  - defaults
dependencies:
  - python=3.8
  - protobuf==3.17.2
  - grpcio==1.42.0
  - pyyaml==6.0
  - numpy==1.21.2
  - requests==2.26.0
  - tensorflow==2.3.0
  - pandas==1.3.4
  - networkx==2.6.3
  - scikit-learn==1.0.1
  - pip:
    - plyvel
