# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import interface.dci.dci_pb2 as dci_dot_dci__pb2


class DockStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeliverTx = channel.unary_stream(
                '/dci.Dock/DeliverTx',
                request_serializer=dci_dot_dci__pb2.RequestDeliverTx.SerializeToString,
                response_deserializer=dci_dot_dci__pb2.ResponseDeliverTx.FromString,
                )
        self.RouterInfo = channel.unary_stream(
                '/dci.Dock/RouterInfo',
                request_serializer=dci_dot_dci__pb2.RequestRouterInfo.SerializeToString,
                response_deserializer=dci_dot_dci__pb2.ResponseRouterInfo.FromString,
                )
        self.RouterTransmit = channel.unary_stream(
                '/dci.Dock/RouterTransmit',
                request_serializer=dci_dot_dci__pb2.RequestRouterTransmit.SerializeToString,
                response_deserializer=dci_dot_dci__pb2.ResponseRouterTransmit.FromString,
                )
        self.RouterPathCallback = channel.unary_stream(
                '/dci.Dock/RouterPathCallback',
                request_serializer=dci_dot_dci__pb2.RequestRouterPathCallback.SerializeToString,
                response_deserializer=dci_dot_dci__pb2.ResponseRouterPathCallback.FromString,
                )
        self.SwitchIsland = channel.unary_unary(
                '/dci.Dock/SwitchIsland',
                request_serializer=dci_dot_dci__pb2.RequestSwitchIsland.SerializeToString,
                response_deserializer=dci_dot_dci__pb2.ResponseSwitchIsland.FromString,
                )
        self.UpdateGraphData = channel.unary_unary(
                '/dci.Dock/UpdateGraphData',
                request_serializer=dci_dot_dci__pb2.RequestUpdateGraphData.SerializeToString,
                response_deserializer=dci_dot_dci__pb2.ResponseUpdateGraphData.FromString,
                )
        self.GetGraphData = channel.unary_unary(
                '/dci.Dock/GetGraphData',
                request_serializer=dci_dot_dci__pb2.RequestGetGraphData.SerializeToString,
                response_deserializer=dci_dot_dci__pb2.ResponseGetGraphData.FromString,
                )


class DockServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeliverTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouterInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouterTransmit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouterPathCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchIsland(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGraphData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraphData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DockServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeliverTx': grpc.unary_stream_rpc_method_handler(
                    servicer.DeliverTx,
                    request_deserializer=dci_dot_dci__pb2.RequestDeliverTx.FromString,
                    response_serializer=dci_dot_dci__pb2.ResponseDeliverTx.SerializeToString,
            ),
            'RouterInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.RouterInfo,
                    request_deserializer=dci_dot_dci__pb2.RequestRouterInfo.FromString,
                    response_serializer=dci_dot_dci__pb2.ResponseRouterInfo.SerializeToString,
            ),
            'RouterTransmit': grpc.unary_stream_rpc_method_handler(
                    servicer.RouterTransmit,
                    request_deserializer=dci_dot_dci__pb2.RequestRouterTransmit.FromString,
                    response_serializer=dci_dot_dci__pb2.ResponseRouterTransmit.SerializeToString,
            ),
            'RouterPathCallback': grpc.unary_stream_rpc_method_handler(
                    servicer.RouterPathCallback,
                    request_deserializer=dci_dot_dci__pb2.RequestRouterPathCallback.FromString,
                    response_serializer=dci_dot_dci__pb2.ResponseRouterPathCallback.SerializeToString,
            ),
            'SwitchIsland': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchIsland,
                    request_deserializer=dci_dot_dci__pb2.RequestSwitchIsland.FromString,
                    response_serializer=dci_dot_dci__pb2.ResponseSwitchIsland.SerializeToString,
            ),
            'UpdateGraphData': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGraphData,
                    request_deserializer=dci_dot_dci__pb2.RequestUpdateGraphData.FromString,
                    response_serializer=dci_dot_dci__pb2.ResponseUpdateGraphData.SerializeToString,
            ),
            'GetGraphData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraphData,
                    request_deserializer=dci_dot_dci__pb2.RequestGetGraphData.FromString,
                    response_serializer=dci_dot_dci__pb2.ResponseGetGraphData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dci.Dock', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Dock(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeliverTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dci.Dock/DeliverTx',
            dci_dot_dci__pb2.RequestDeliverTx.SerializeToString,
            dci_dot_dci__pb2.ResponseDeliverTx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RouterInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dci.Dock/RouterInfo',
            dci_dot_dci__pb2.RequestRouterInfo.SerializeToString,
            dci_dot_dci__pb2.ResponseRouterInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RouterTransmit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dci.Dock/RouterTransmit',
            dci_dot_dci__pb2.RequestRouterTransmit.SerializeToString,
            dci_dot_dci__pb2.ResponseRouterTransmit.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RouterPathCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dci.Dock/RouterPathCallback',
            dci_dot_dci__pb2.RequestRouterPathCallback.SerializeToString,
            dci_dot_dci__pb2.ResponseRouterPathCallback.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SwitchIsland(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dci.Dock/SwitchIsland',
            dci_dot_dci__pb2.RequestSwitchIsland.SerializeToString,
            dci_dot_dci__pb2.ResponseSwitchIsland.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateGraphData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dci.Dock/UpdateGraphData',
            dci_dot_dci__pb2.RequestUpdateGraphData.SerializeToString,
            dci_dot_dci__pb2.ResponseUpdateGraphData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGraphData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dci.Dock/GetGraphData',
            dci_dot_dci__pb2.RequestGetGraphData.SerializeToString,
            dci_dot_dci__pb2.ResponseGetGraphData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
